[package]
name = "radsuite-tauri"
version = "0.2.5"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
radsuite-desktop = { path = "../../../crates/radsuite-desktop" }
serde_json.workspace = true
tauri = { workspace = true, features = ["protocol-asset"] }
tauri-plugin-dialog.workspace = true
tauri-plugin-process.workspace = true
tauri-plugin-updater.workspace = true
